---

cadvisor_version: 0.45.0

cadvisor_container_name: cadvisor
cadvisor_container_image_name: gcr.io/cadvisor/cadvisor
cadvisor_container_image_tag: ~
cadvisor_container_image_ref: >-
  {{ cadvisor_container_image_name }}:{{ cadvisor_container_image_tag | default('v' + cadvisor_version, True) }}
cadvisor_container_volumes: >-
  {{ cadvisor_container_base_volumes + cadvisor_container_extra_volumes | default([], True) }}
cadvisor_container_extra_volumes: ~
cadvisor_container_env: ~
cadvisor_container_labels: "{{ cadvisor_container_base_labels | combine(cadvisor_container_extra_labels) }}"
cadvisor_container_extra_labels: {}
cadvisor_container_ports: ~
cadvisor_container_networks: ~
cadvisor_container_etc_hosts: ~
cadvisor_container_devices: [ "/dev/kmsg:/dev/kmsg:rwm" ]
cadvisor_container_privileged: yes
cadvisor_container_pid_mode: "host"
cadvisor_container_userns_mode: "host"
cadvisor_container_capabilities: ~
cadvisor_container_restart_policy: unless-stopped
cadvisor_container_command: >-2
  {{ ["--docker_only=false"]
    + (["--disable_metrics=" + cadvisor_disabled_metrics | join( ',' )]
      if cadvisor_disabled_metrics | default(false, True) else [])
    + (["--enable_metrics=" +  cadvisor_force_enable_metrics | join( ',' )]
      if cadvisor_force_enable_metrics | default(false, True) else [])
  }}
cadvisor_container_base_labels:
  version: "{{ cadvisor_version }}"
cadvisor_container_base_volumes:
  - "/:/rootfs:ro"
  - "/var/run:/var/run:ro"
  - "/sys:/sys:ro"
  - "/var/lib/docker/:/var/lib/docker:ro"
  - "/dev/disk/:/dev/disk:ro"

cadvisor_disabled_metrics:
  - advtcp
  - cpu_topology
  - cpuset
  - hugetlb
  - memory_numa
  - process
  - referenced_memory
  - resctrl
  - sched
  - tcp
  - udp
cadvisor_force_enable_metrics: []
