namespace: finallycoffee
name: observability
version: 0.1.0
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Various ansible roles useful for automating infrastructure
dependencies:
  "community.docker": "^3.0.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/observability
issues: https://codeberg.org/finallycoffee/ansible-collection-observability/issues
tags:
  - observability
  - monitoring
  - prometheus
  - victoriametrics
  - grafana
