---

matrix_alertmanager_prefix: ""
matrix_alertmanager_user: "mxalerts"
matrix_alertmanager_base_path: "/opt/matrix-alerts"
matrix_alertmanager_config_file_path: "{{ matrix_alertmanager_base_path }}/env"

matrix_alertmanager_listen_port: 3000
matrix_alertmanager_secret: ~
matrix_alertmanager_homeserver_url: ~
matrix_alertmanager_rooms: []
matrix_alertmanager_mxid: ~
matrix_alertmanager_access_token: ~
matrix_alertmanager_mention_room: false

matrix_alertmanager_container_name: matrix-alerts
matrix_alertmanager_container_image_name: "docker.io/jaywink/matrix-alertmanager"
matrix_alertmanager_container_image_tag: latest
matrix_alertmanager_container_image: >-2
  {{ matrix_alertmanager_container_image_name + ':' + matrix_alertmanager_container_image_tag }}
matrix_alertmanager_container_env: >-2
  {{ matrix_alertmanager_container_base_env | combine(matrix_alertmanager_container_extra_env) }}
matrix_alertmanager_container_extra_env: {}
matrix_alertmanager_container_ports: >-2
  {{ matrix_alertmanager_container_base_ports + matrix_alertmanager_container_extra_ports }}
matrix_alertmanager_container_extra_ports: []
matrix_alertmanager_container_networks: []
matrix_alertmanager_container_purge_networks: false
matrix_alertmanager_container_volumes: >-2
  {{ matrix_alertmanager_container_base_volumes + matrix_alertmanager_container_extra_volumes }}
matrix_alertmanager_container_extra_volumes: []
matrix_alertmanager_container_labels: >-2
  {{ matrix_alertmanager_container_base_labels | combine(matrix_alertmanager_container_extra_labels) }}
matrix_alertmanager_container_extra_labels: {}
matrix_alertmanager_container_capabilities: ~
matrix_alertmanager_container_etc_hosts: ~
matrix_alertmanager_container_restart_policy: unless-stopped
