---
- name: Ensure cadvisor container image '{{ cadvisor_container_image_ref }}' is {{ cadvisor_state }}
  community.docker.docker_image:
    name: "{{ cadvisor_container_image_ref }}"
    state: "{{ cadvisor_state }}"
    source: "{{ cadvisor_container_image_source }}"
    force_source: "{{ cadvisor_container_image_force_source }}"

- name: Ensure cadvisor container '{{ cadvisor_container_name }}' is {{ cadvisor_container_state }}
  community.docker.docker_container:
    name: "{{ cadvisor_container_name }}"
    image: "{{ cadvisor_container_image_ref }}"
    env: "{{ cadvisor_container_env | default(omit, true) }}"
    ports: "{{ cadvisor_container_ports | default(omit, true) }}"
    labels: "{{ cadvisor_container_labels }}"
    devices: "{{ cadvisor_container_devices }}"
    volumes: "{{ cadvisor_container_volumes }}"
    networks: "{{ cadvisor_container_networks | default(omit, true) }}"
    etc_hosts: "{{ cadvisor_container_etc_hosts | default(omit, true) }}"
    privileged: "{{ cadvisor_container_privileged }}"
    command: "{{ cadvisor_container_command }}"
    pid_mode: "{{ cadvisor_container_pid_mode | default(omit, true) }}"
    userns_mode: "{{ cadvisor_container_userns_mode | default(omit, true) }}"
    restart_policy: "{{ cadvisor_container_restart_policy }}"
    state: "{{ cadvisor_container_state }}"
