---

alertmanager_user: alertmanager
alertmanager_version: 0.25.0
alertmanager_base_path: /opt/alertmanager
alertmanager_config_path: "{{ alertmanager_base_path }}/config"
alertmanager_config_file: "{{ alertmanager_config_path }}/alertmanager.yml"
alertmanager_data_path: "{{ alertmanager_base_path }}/data"

alertmanager_container_name: alertmanager
alertmanager_container_image_name: alertmanager
alertmanager_container_image_namespace: prometheus/
alertmanager_container_image_registry: quay.io

alertmanager_container_image_repository: >-
  {{
    (container_registries[alertmanager_container_image_registry] | default(alertmanager_container_image_registry))
    + '/' + (alertmanager_container_image_namespace | default(''))
    + alertmanager_container_image_name
  }}
alertmanager_container_image_reference: >-
  {{
    alertmanager_container_image_repository + ':'
    + (alertmanager_container_image_tag | default('v' + alertmanager_version))
  }}

alertmanager_container_image_force_pull: "{{ alertmanager_container_image_tag is defined }}"

alertmanager_container_default_volumes:
  - "{{ alertmanager_config_file }}:/etc/alertmanager/alertmanager.yml:ro"
  - "{{ alertmanager_data_path }}:/alertmanager:rw"
alertmanager_container_volumes: >-
  {{ alertmanager_container_default_volumes
     + alertmanager_container_extra_volumes | default([]) }}
alertmanager_container_restart_policy: "unless-stopped"

alertmanager_config:
  global: {}
  route: {}
  receivers: []
