---
- name: Ensure alertmanager is restarted
  community.docker.docker_container:
    name: "{{ alertmanager_container_name }}"
    state: "{{ alertmanager_container_state }}"
    restart: true
  listen: restart-alertmanager
  when: alertmanager_deployment_method == 'docker'
